# the subject system to perform the experiments with
# available datasets:
# - apache-httpd
# - argouml-spl
# - berkeley-db-libdb
# - busybox
# - dia
# - irssi
# - libssh
# - openvpn
# - vim
datasets=apache-httpd,argouml-spl,berkeley-db-libdb,busybox,dia,irssi,libssh,openvpn,vim

# the number of repetitions for each scenario
numberOfRepetitions=30

# the minimum number of features in a sampled product variant
minVariantFeatures=5

# the maximum number of features in a sampled product variant
maxVariantFeatures=10

# the location of the ground truth, created by VEVOS
vevosGroundTruthDatasetPath=/home/user/ground_truth/

# the different numbers of product variants in scenarios
numbersOfVariants=3,5,7

# the different percentages of available proactive feature traces in scenarios
featureTracePercentages=0,5,10,15,20,25

# the different percentages of erroneous proactive feature traces of available feature traces
mistakePercentages=0,25,50,75,100

# the way proactive and retroactive presence conditions are combined for each node in the ECCO tree
# available evaluation Strategies:
# - at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerProactiveBasedEvaluation (use proactive presence condition if available)
# - at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerRetroactiveBasedEvaluation (use retroactive presence conditions)
# - at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerProactiveAdditionEvaluation (use a disjunction of proactive and retroactive presence condition)
# - at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerProactiveSubtractionEvaluation (use a conjunction fo proactive and retroactive presence condition)
evaluationStrategies=at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerProactiveBasedEvaluation

# the type of mistake that is inserted into presence conditions
# available mistake strategies:
# - SwappedFeature (use another random feature instead of the correct one)
# - SwappedCondition (use another random existing presence condition instead of the correct one)
# - ErroneousConjunction (conjunct the correct condition with another random feature)
# - SwappedOperator (use another operator (AND/OR) instead of the correct one)
# - MissingConjunction (remove a conjunction and only use on part of it)
# - NoMistake (make no mistake)
mistakeStrategies=SwappedFeature,SwappedCondition,ErroneousConjunction

# available trace pickers
# - anon.ecco.experiment.picker.featuretracepicker.RandomFeatureTracePicker (select random feature traces for e.g. available feature traces in the experiment or to insert mistakes into)
# - anon.ecco.experiment.picker.featuretracepicker.SingleAssociationTracePicker (select exactly one feature trace per association in ECCO)
tracePickers=anon.ecco.experiment.picker.featuretracepicker.RandomFeatureTracePicker

# available boosting configurations: ENABLED, DISABLED, BOTH
boosting=BOTH
