datasets=apache-httpd,argouml-spl,berkeley-db-libdb,busybox,dia,irssi,libssh,openvpn,vim
numberOfRepetitions=30
minVariantFeatures=5
maxVariantFeatures=10
vevosGroundTruthDatasetPath=/home/user/ground_truth/
numbersOfVariants=3,5,7
featureTracePercentages=0,5,10,15,20,25
mistakePercentages=0,25,50,75,100
# available evaluation Strategies:
# - at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerProactiveBasedEvaluation
# - at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerRetroactiveBasedEvaluation
# - at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerProactiveAdditionEvaluation
# - at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerProactiveSubtractionEvaluation
evaluationStrategies=at.jku.isse.ecco.storage.ser.featuretrace.evaluation.SerProactiveBasedEvaluation
# available mistake strategies:
# - SwappedFeature
# - SwappedCondition
# - ErroneousConjunction
# - SwappedOperator
# - MissingConjunction
# - NoMistake
mistakeStrategies=SwappedFeature,SwappedCondition,ErroneousConjunction
# available trace pickers
# - anon.ecco.experiment.picker.featuretracepicker.RandomFeatureTracePicker
# - anon.ecco.experiment.picker.featuretracepicker.SingleAssociationTracePicker
tracePickers=anon.ecco.experiment.picker.featuretracepicker.RandomFeatureTracePicker
# available boosting configurations: ENABLED, DISABLED, BOTH
boosting=BOTH

# 30 (repetitions) x 3 (variants) x 2 (boost) x (1 (0ft) + 5 (ft/0 per 0m) + 5 (ft/0) x 4 (m/0) x 3 (mistake types)
# 2 x (6 + 5 x 4 x 3) with same committed variant configs = 132


